version: "3.7"
services: 
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: k8s-sample-app
    container_name: k8s-sample-app
    ports:
      - "3000:3000"
    env_file:
      - common.env
    depends_on:
      - redis
  redis:
    image: redis:4
    container_name: k8s-sample-db
    volumes:
      - ./db/data:/data
    ports:
      - "6379:6379"
    env_file:
      - common.env
